name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f8c42dc14e9e2eceb1a9f78af60092d771e05db537a0b1cd98b94eda4041d93"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
