name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f968963f05cb6c667eea05bc2d6280e65893aa9184502e264ff3a008fcd9806b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
