name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796f63af34845a6a4aeeee33396b80a5e57ec5fa1e4d6c6e6000fbadfc43deb3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
