name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9879f857fb65bd194703cd28fe4a9678a238eebfc03515ba574e6cc90818a747"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
