name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c18dc2c6ffadf04b54633a1ad1d0798315e188273acbfd2927dbefcb8d74df65"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
